remote_theme : MyeongJH/myeongjh.github.io

# Site settings
title: MyeongJH
description: Myeong's Portfolios
baseurl: ""
url: "https://myeongjh.github.io" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Jaehwan Myeong
user_title: Web Developer
user_description: 명재환 테스트
email: myeong1001@gmail.com
github_username:  MyeongJH

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
